/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetExperience"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEducation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProjectBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CourseDto: {
            name: string;
            /** Format: double */
            credits: number;
            level: components["schemas"]["CourseLevel"];
            /** Format: date */
            completedOn: string;
            highlighted: boolean;
        };
        /** @enum {unknown} */
        CourseLevel: "basic" | "advanced";
        CourseOverviewDto: {
            /** Format: double */
            totalCredits: number;
            courses: components["schemas"]["CourseDto"][];
        };
        LinkDto: {
            label: string;
            url: string;
        };
        ProfileDto: {
            name: string;
            headline: string;
            summary: string;
            links: components["schemas"]["LinkDto"][];
            skills: components["schemas"]["SkillGroupDto"][];
            languages: components["schemas"]["SpokenLanguageDto"][];
        };
        ProjectDto: {
            slug: string;
            title: string;
            summary: string;
            technologies: string[];
            /** Format: date */
            startedOn: string;
            /** Format: date */
            finishedOn: null | string;
            repositoryUrl: null | string;
        };
        SkillGroupDto: {
            category: string;
            items: string[];
        };
        SpokenLanguageDto: {
            name: string;
            proficiency: string;
        };
        TimelineEntryDto: {
            organization: string;
            role: string;
            location: null | string;
            /** Format: date */
            startedOn: string;
            /** Format: date */
            finishedOn: null | string;
            highlights: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetProfile: {
        parameters: {
            query?: {
                /** @description Content language. Defaults to "en". */
                lang?: "en" | "sv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDto"];
                };
            };
        };
    };
    GetExperience: {
        parameters: {
            query?: {
                /** @description Content language. Defaults to "en". */
                lang?: "en" | "sv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryDto"][];
                };
            };
        };
    };
    GetEducation: {
        parameters: {
            query?: {
                /** @description Content language. Defaults to "en". */
                lang?: "en" | "sv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryDto"][];
                };
            };
        };
    };
    GetCourses: {
        parameters: {
            query?: {
                /** @description Content language. Defaults to "en". */
                lang?: "en" | "sv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOverviewDto"];
                };
            };
        };
    };
    GetProjects: {
        parameters: {
            query?: {
                /** @description Content language. Defaults to "en". */
                lang?: "en" | "sv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"][];
                };
            };
        };
    };
    GetProjectBySlug: {
        parameters: {
            query?: {
                /** @description Content language. Defaults to "en". */
                lang?: "en" | "sv";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
